# -*- after-save-hook: (lambda () (org-latex-export-to-pdf t)) org-export-before-parsing-hook: (org-export-before-parsing-mathnotes) -*-
#+LATEX_CLASS: mathnotes
#+TITLE: MATH 455 (Honours Analysis 4)
#+AUTHOR: J. Han
#+PROPERTY: ANKI_DECK /edu/math/455/

* preamble

The following notes are adapted from lectures given by Dmitry Jakobson in Winter 2024.
All errors in interpretation, reasoning, coherence, and articulation are my own.

This document's source code, located at https://github.com/brunefig/math455/blob/main/notes.org,
can be converted into [[https://apps.ankiweb.net/][Anki]] flashcards with the [[https://github.com/louietan/anki-editor/][\texttt{anki-editor}]] package for [[https://www.gnu.org/software/emacs/][GNU Emacs]].
Flashcard [[https://en.wikipedia.org/wiki/Cloze_test][cloze deletions]] are typeset in {{c1::magenta}}.

* preliminaries
** topological spaces
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::topological space}} $(X,\tau)$ is a {{c2::set}}
$X$ endowed with a {{c2::topology}} $\tau$.
*** topology
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::topology}} $\tau$ on a set $X$ is a collection of sets
that contains {{c2::$\emptyset$ and $X$}}
and is closed under {{c2::finite intersections and arbitrary unions}}.
Membership in $\tau$ defines {{c3::an open set}} in {{c1::the topological space $(X,\tau)$}}.
* 2024-01-05 topology & metric spaces
** connectedness
*** connected space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $(X,\tau)$ is {{c1::a <<<connected space>>>}} iff
$\neg \exists U,U' \in$
{{c2::$\tau \setminus \{\emptyset\}$}} :
{{c2::$U \cap U'$ = $\emptyset$}}
$\land$ {{c2::$X$ = $U \cup U'$}}.
*** connected set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a topological space $(X,\tau)$,
$A \subseteq X$ is {{c1::a <<<connected>>> set}} iff
$\neg \exists U,U' \in$ {{c2::$\tau$}} :
{{c3::$A \cap U \neq \emptyset$}},
{{c3::$A \cap U' \neq \emptyset$}},
{{c3::$U \cap U'$ = $\emptyset$}},
{{c3::$A$ = $(U \cap A) \cup (U' \cap A)$}}.
*** path connectedness
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ is {{c1::a <<<path connected>>> space}} iff
{{c2::$\forall x,x' \in X$ :
$\exists$ continuous $f : [0,1] \rightarrow X$ :
$[f(0)$ = $x$
$\land$
$f(1)$ = $x']$}}.
**** path connected implies connected
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
{{c2::All}} path connected spaces are {{c1::connected spaces}}.
**** connectedness is equivalent to path connectedness in R^n
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For {{c1::open}} sets in {{c1::$\mathbb{R}^n$}},
{{c2::connectedness}} is equivalent to {{c3::path connectedness}}.
*** connected components
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ can be expressed as
{{c1::the disjoint union of maximal connected subsets}},
where a connected subset is called maximal iff
{{c1::it has no connected superset in $X$}}.
These subsets are the {{c2::<<<connected components>>>}} of $X$.
**** path components
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
A topological space $X$ can be expressed as
{{c1::the disjoint union of maximal path connected subsets}},
where a path connected subset is called maximal iff
{{c1::it has no path connected superset in $X$}}.
These subsets are the {{c2::<<<path components>>>}} of $X$.
***** path connected spaces have one path component
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
A {{c1::path connected}} space has exactly one {{c2::path component}}.
***** connected does not imply path connected
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
{{c1::$\Bigl\{\Bigl(x,\sin\left(\frac{1}{x}\right)\Bigr) \Bigm| x \in (0,1]\,\Bigr\} \cup \{(0,0)\}$}}
$\subseteq \mathbb{R}^2$ is
{{c2::connected}} but not {{c2::path connected}}
because {{c3::it has two path components}}.
*** continuous image of a connected set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $f$ : $X \rightarrow \mathbb{R}$ is continuous,
$A \subseteq X$ is connected, and
$x,x' \in f(A)$
such that $x < x'$,
then {{c1::$[x,x'] \subseteq f(A)$}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
If $f$ : $X \rightarrow \mathbb{R}$ is continuous,
$A \subseteq X$ is connected, and
$x,x' \in f(A)$
such that $x < x'$, prove that

$[x,x'] \subseteq f(A)$.
***** Back
Suppose $\exists c \in \bigl(f(x'),f(x)\bigr)$ : $c \notin f(A)$.
Since
$f^{-1}\bigl((-\infty,c)\bigr)$
and
$f^{-1}\bigl((c,\infty)\bigr)$
are open,
$A \subseteq f^{-1}\bigl((-\infty,c)\bigr) \cup f^{-1}\bigl((c,\infty)\bigr)$
is not connected.
** examples of metric spaces
*** induced metric for a normed vector space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Any normed vector space is a metric space with the induced metric

$d(x,x')$ := {{c1::$\|x-x'\|$}}.
*** l_p
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For $p \in$ {{c1::$(0,\infty)$}},

{{c2::$l_p$}} :=
{{c3::$\left\{(x_n)_{n \in \mathbb{N} } \in \mathbb{C}^{\mathbb{N} } \,\middle| \sum_{n \in \mathbb{N} } |x_n|^p < \infty\right\}$}}

is a normed vector space with

$\|x\|_p$ :=
{{c3::$\bigl(\sum_{n \in \mathbb{N} } |x_n|^p\bigr)^{1/p}$}}.
**** 1/n sequence
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
The sequence $\left(\frac{1}{n}\right)_{n \in \mathbb{Z}_+}$
is a member of $l_p$
iff {{c1::$p > 1$}}.
***** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
Prove that
$\left(\frac{1}{n}\right)_{n \in \mathbb{Z}_+} \in l_p$
iff $p > 1$.
****** Back
$\left(\frac{1}{n}\right)_{n \in \mathbb{Z}_+} \in l_p$
$\iff$
$\sum_{n \in \mathbb{Z}_+} \left(\frac{1}{n}\right)^p < \infty$
$\iff$
$p > 1$.
*** L_p
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For $p \in$ {{c1::$[1,\infty)$}},

{{c2::$L^p([a,b])$}} :=
{{c3::$\left\{f(x) \,\middle| \int_a^b |f(x)|^p dx < \infty\right\}$}}

is a normed vector space with

$\|f\|_p$ :=
{{c3::$\left(\int_a^b |f(x)|^p dx\right)^{1/p}$}}.
*** symmetric difference metric
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
$d(A,A')$ :=
$\text{vol}_n(A \triangle A')$
is a possible metric on {{c1::$\mathbb{R}^n$}}.
*** Hausdorff
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a metric space $(X,d)$,
a set $A \subseteq X$,
and $\epsilon > 0$,
let $A_\epsilon$ :=
{{c1::$\bigcup_{x \in A} B(x,\epsilon)$}}.
Then the {{c2::<<<Hausdorff>>>}} metric is

{{c2::$d_H(A,A')$}} := {{c3::$\inf \bigl\{\,\epsilon > 0 \bigm| A' \subseteq A_\epsilon \land A \subseteq A'_\epsilon\bigr\}$}}.
*** $p\text{-adic}$ numbers
**** normed vector space of rational numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
Given a fixed prime $p$,
{{c1::\[\forall q \in \mathbb{Q} \setminus \{0\} : \exists (a,b,n) \in \mathbb{Z}^3 : \left[\,q = p^n \cdot \frac{a}{b} \land\, \gcd(a,p) = \gcd(b,p) = 1\,\right]\]}}
and {{c2::$\mathbb{Q}$}} is a normed vector space with

$\|q\|_p$ := {{c3::$\begin{cases} p^{-n} & q \neq 0 \\ 0 & q = 0 \end{cases}$}}.
***** p = 2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The 2-adic norm of $\frac{96}{7}$ is
{{c1::$\frac{1}{32}$}}.
***** p = 3
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The 3-adic norm of $3^{-2024} \cdot \frac{8}{13}$ is
{{c1::$3^{2024}$}}.
***** intuition for the p-adic norm
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The {{c3::$p\text{-adic}$}} norm
$\|q\|_p$ is {{c1::small}}
if $q$ is {{c2::divisible by a large power of $p$}}.
***** intuition for the p-adic norm of zero
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The $p\text{-adic}$ norm of $0$ is $0$ because
{{c1::$0$ is divisible by any power of $p$}}.
**** COMMENT completion of Q wrt the p-adic norm
***** p-adic rationals
\lim \|x\|_p = \|a_n p^n + a_{n+1} p^{n+1} + \dots\|_p \rightarrow 0
this set of Laurent series is $\mathbb{Q}_p$, the p-adic rational numbers
**** product formula for /p/-adic norms of rational numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
(/p/-adic product formula.)
If $q \in$ {{c1::$\mathbb{Q} \setminus \{0\}$}}, then
{{c2::$|q| \cdot \prod_{p \text{ prime} } \|q\|_p$}} = {{c3::$1$}}.
**** COMMENT difference between mathematicians, physicists, and engineers
math: 9 is a counterexample
physicists: 9 is an experimental error
engineer: 9 is prime
** convexness
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A set $X$ is {{c1::<<<convex>>>}} when
{{c2::the line segment joining any two points in $X$ lies within $X$}}.
* 2024-01-10 contraction mappings & product topology
$\alpha \in I$ henceforth refers to members of a possibly uncountable index set $I$.
** arbitrary union of intersecting connected sets is connected
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
*** Cloze
If $\{A_\alpha\}_{\alpha \in I}$ is a family of {{c1::connected}} sets
in a topological space $X$
such that $\forall \alpha,\alpha' \in I$ :
{{c1::$A_\alpha \cap A_{\alpha'} \neq \emptyset$}},
then {{c3::$\bigcup_{\alpha \in I} A_\alpha$}} is {{c2::connected}}.
*** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
If $\{A_\alpha\}_{\alpha \in I}$ is a family of connected sets in $X$
such that $\forall \alpha,\alpha' \in I$ :
$A_\alpha \cap A_{\alpha'} \neq \emptyset$,
prove that $\bigcup_{\alpha \in I} A_\alpha$ is connected.
**** Back
Suppose $A$ := $\bigcup_{\alpha \in I} A_\alpha$ is not connected.
Let $U,U' \subseteq X$ be open and nonempty relative to $A$
such that $U \cap U'$ = $\emptyset$ and $A$ = $U \cup U'$.
Since each $A_\alpha$ is connected, there is no $\alpha$ for which
$A_\alpha \cap U \neq \emptyset \neq A_\alpha \cap U'$.
But then $\exists \alpha,\alpha' \in I$ : $A_\alpha \subseteq U \land A_{\alpha'} \subseteq U'$,
which contradicts that $A_\alpha \cap A_{\alpha'} \neq \emptyset$.
** total disconnectedness
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ is {{c1::totally disconnected}}
when {{c2::every connected subset of $X$ is a singleton}}.
*** totally disconnected subspaces of R
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::totally disconnected}} space in $\mathbb{R}$
contains {{c3::only}} {{c2::points}} and {{c3::no}} {{c2::intervals}}.
*** Cantor set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c1::The Cantor set}} is a totally disconnected space in $\mathbb{R}$.
** contraction mappings
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a metric space $(X,d)$,
$T$ : {{c1::$X$}} $\rightarrow$ {{c1::$X$}}
is {{c2::a contraction mapping}} when
{{c3::$\exists c \in [0,1)$ : $\forall x,x' \in X$ :
$d\bigl(T(x),T(x')\bigr) \le c \cdot d(x,x')$}}.
*** contraction mappings are continuous
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
All contraction mappings are {{c1::continuous}}.
*** orbit of a contraction mapping is a Cauchy sequence
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
(<<<Orbit lemma>>>.)
For $x \in X$, the {{c1::orbit}} {{c2::$\bigl(T^n(x)\bigr)_{n \in \mathbb{N} }$}}
of a {{c3::contraction mapping}} $T$ on $X$
is {{c4::a Cauchy sequence}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
(Orbit lemma.)
For $x \in X$, prove that the orbit
$\bigl(T^n(x)\bigr)_{n \in \mathbb{N}}$
of a contraction mapping $T$ on $X$
is a Cauchy sequence.
***** Back
For $n \in \mathbb{Z}_+$,
\[\begin{align*}
d\left(T^n(x),T^{n+1}(x)\right)
&< c \cdot d\left(T^{n-1}(x),T^n(x)\right) \\
&< c^2 \cdot d\left(T^{n-2}(x),T^{n-1}(x)\right) \\
\cdots &< c^n \cdot d\bigl(x,T(x)\bigr).
\end{align*}\]
Let $m \ge n$.
By the triangle inequality,
\[\begin{align*}
d\left(T^n(x),T^m(x)\right)
&\le \sum_{k=n}^{m-1} d\left(T^k(x),T^{k+1}(x)\right) \\
&\le d\bigl(x,T(x)\bigr) \sum_{k=n}^{m-1} c^k \\
&= c^n \cdot d\bigl(x,T(x)\bigr) \sum_{k=0}^{m-n-1} c^k \\
&\le \frac{c^n \cdot d\bigl(x,T(x)\bigr)}{1-c}.
\end{align*}\]
For $\epsilon > 0$, choosing
$n > \log_c \left(\frac{\epsilon}{2} \cdot \frac{1-c}{d\bigl(x,T(x)\bigr)}\right)$
and $m,m' \ge n$ guarantees
\[\begin{align*}
d\bigl(T(m),T(m')\bigr) &\le \\
d\bigl(T(n),T(m)\bigr) + d\bigl(T(n),T(m')\bigr)
&< \epsilon.
\end{align*}\]
*** existence, uniqueness, and properties of a fixed point
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
({{c3::<<<Contraction mapping theorem>>>}}.)
If $(X,d)$ is a {{c1::nonempty}} and {{c1::complete}} metric space
and $T$ is {{c1::a contraction mapping on $X$}}, then
{{c2::\[\exists ! z \in X : T(z) = z,\]}}
i.e. $z$ is {{c2::the unique fixed point}},
and
{{c2::\[\forall x \in X : \lim_{n \rightarrow \infty} T^n(x) = z,\]}}
where {{c2::$\forall n \in \mathbb{N}$ : $T^n(x)$ :=
$\underset{n \text{ times} }{T(T(\cdots T}(x)))$}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
(Contraction mapping theorem.)
If $(X,d)$ is a nonempty and complete metric space
and $T$ is a contraction mapping on $X$, prove that
\[\exists ! z \in X : T(z) = z\]
and
\[\forall x \in X : \lim_{n \rightarrow \infty} T^n(x) = z,\]
where $\forall n \in \mathbb{N}$ : $T^n(x)$ :=
$\underset{n \text{ times} }{T(T(\cdots T}(x)))$.
***** Back
For $x \in X$,
$T(x)$ is Cauchy by the orbit lemma,
and since $(X,d)$ is complete it converges to some point $z \in X$.
Then $z$ is a fixed point of $T$ because
\[\begin{align*}
T^n(x) \rightarrow z
&\implies T(T^n(x)) \rightarrow T(z) \\
&\implies T(T^n(x)) = T^{n+1}(x) \rightarrow z = T(z),
\end{align*}\]
and is its unique fixed point because
\[T(z) = z \land T(z') = z'
\implies d(z,z') \le c \cdot d(z,z') \iff d(z,z') = 0.\]
**** example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
$x \mapsto \frac{x}{2}$ is a contraction mapping on $(\mathbb{R},|\cdot|)$
with fixed point $z$ = {{c1::$0$}}.
** iterated function systems and fixed point sets
$\mathcal{K}(X)$ henceforth denotes the set of compact subsets of a set $X$.
*** COMMENT from PS2
Define a metric space $(X,d_H)$
such that $X$ is the set of compact subsets of $\mathbb{R}$
and $d_H$ is the Hausdorff distance.
Problem (PS2): $F$ : $(X,d_H) \rightarrow (X,d_H)$
is a contracting map.
*** fixed point set of a union of contraction mapping images of compact sets
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $m \in \mathbb{Z}_+$,
$\left\{T_n : \mathbb{R}^d \rightarrow \mathbb{R}^d\right\}_{n \in [m]}$
are contraction mappings, and
{{c1::\[F : \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr) \rightarrow \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr) : A \mapsto \bigcup_{n \in [m]} T_n(A),\]}}
then
{{c3::$\exists ! A \in \mathcal{K}(\mathbb{R}^d)$ : $F(A) = A$}}.
This is the {{c3::<<<fixed point set>>>}} of $F$.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
For $m \in \mathbb{Z}_+$
and contraction mappings
$\left\{T_n : \mathbb{R}^d \rightarrow \mathbb{R}^d\right\}_{n \in [m]}$,
let
\[F : \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr) \rightarrow \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr)\]
such that
$F(A)$ = $\bigcup_{n \in [m]} T_n(A)$.
Prove that
\[\exists ! A \in \mathcal{K}(X) : F(A) = A.\]
***** Back
$F$ is a contraction mapping (to be demonstrated in problem set 2),
and $\bigl(\mathcal{K}(X),d_H\bigr)$ is a complete metric space (???).
A unique fixed point set thus exists by the contraction mapping theorem.
**** Cantor set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
Let $T_0,T_1$ : $\mathbb{R} \rightarrow \mathbb{R}$ such that
$T_0(x)$ := {{c1::$\frac{x}{3}$}} and
$T_1(x)$ := {{c1::$\frac{x+2}{3}$}} and
$F(A)$ : $\mathcal{K}(\mathbb{R}) \rightarrow \mathcal{K}(\mathbb{R})$ such that
$F(A)$ := $T_0(A) \cup T_1(A)$.
Then

$F\bigl([0,1]\bigr)$ =
{{c3::$T_0\bigl([0,1]\bigr) \cup T_1\bigl([0,1]\bigr)$ = $\left[0,\frac{1}{3}\right] \cup \left[\frac{2}{3},1\right]$}},

and the {{c2::fixed point set}} of $F$ is {{c4::the middle-thirds Cantor set}}.
**** iterated function systems
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
If $T_0, T_1$ : $\mathbb{R}^d \rightarrow \mathbb{R}^d$
are {{c2::contraction mappings}} and
$F$ : $\bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr)$
$\rightarrow$
$\bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr)$
such that
$F(A)$ = $T_0(A) \cup T_1(A)$,
then the composition of $F$ with itself is

{{c1::\[F^2(A) = T_0\bigl(T_0(A)\bigr) \cup T_0\bigl(T_1(A)\bigr) \cup T_1\bigl(T_0(A)\bigr) \cup T_1\bigl(T_1(A)\bigr).\]}}
** basis for a topology
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::basis}} $\mathcal{B}$
for a topology $\tau$
is {{c2::a subset of $\tau$ such that $\forall A \in \tau$ : $\exists \{A_\alpha\}_{\alpha \in I} \subseteq \mathcal{B}$ : $A = \bigcup_{\alpha \in I} A_\alpha$}}.
*** open intervals in R
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c1::The open intervals}} form a basis for {{c2::the standard topology}} on $\mathbb{R}$.
*** open balls in a metric space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a metric space $X$,
{{c1::$\bigl\{B(x,\epsilon) \bigm| x \in X, \epsilon > 0\bigr\}$}}
is a basis for {{c2::the open sets in $X$}}.
*** basis is an open cover
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $\mathcal{B}$ is a basis for the topology on $X$, then
$\forall x \in X$ :
{{c1::$\exists U \in \mathcal{B}$ : $x \in U$}}.
*** intersection of sets in a basis
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $\mathcal{B}$ is a basis for the topology $\tau$ on $X$, then
{{c1::$\bigl[U,U' \in \mathcal{B} \land x \in U \cap U'\bigr]$}}
$\implies$
{{c2::$\exists U'' \in \tau$ : $x \in U'' \subseteq U \cap U'$}}.
*** basis defines continuity of a function
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $f$ : $X \rightarrow Y$ for {{c3::topological spaces}} $(X,\tau_X)$ and $(Y,\tau_Y)$
and $\mathcal{B}$ is a basis for $\tau_Y$,
then {{c1::$f$ is continuous}} iff {{c2::$\forall U \in \mathcal{B}$ : $f^{-1}(U) \in \tau_X$}}.
** product topology
*** cylinder sets
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For {{c3::topological spaces}}
$\bigl\{(X_\alpha,\tau_\alpha)\bigr\}_{\alpha \in I}$,
{{c1::$\prod_{\alpha \in I} A_\alpha$}}
is {{c4::a cylinder set}} in
$X$ :=
{{c2::$\prod_{\alpha \in I} X_\alpha$}}
iff
{{c1::$\forall \alpha \in I$ : $A_\alpha \in \tau_\alpha$}}.
**** open rectangles are cylinder sets in R^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
If $X$ := $\mathbb{R}^2$ = $\mathbb{R} \times \mathbb{R}$,
then $\forall$ {{c3::open intervals $(a,b), (a',b') \subseteq \mathbb{R}$}} :
{{c1::$(a,b) \times (a',b')$}}
is {{c2::a cylinder set}} in $X$.
**** basis for a product topology
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For {{c3::topological spaces}}
$\bigl\{X_\alpha\bigr\}_{\alpha \in I}$,
consider a {{c1::cylinder set $\prod_{\alpha \in I} A_\alpha$}} in
$X$ := {{c2::$\prod_{\alpha \in I} X_\alpha$}} such that
{{c1::$\exists I' \subseteq I$ : $\bigl[|I'| \in \mathbb{N} \land \forall \alpha \in I \setminus |I'|$ : $A_\alpha = X_\alpha\bigr]$}}.
These base cylinder sets form a basis for {{c4::the product topology on $X$}}.
*** projection maps
**** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For a vector $x$ := $(x_\alpha)_{\alpha \in I}$
in possibly uncountable dimensions, the function

{{c3::$\pi_\alpha(x)$}} := {{c1::$x_\alpha$}}

is {{c2::a <<<projection map>>>}}.
*** continuity of functions with a product space codomain
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** COMMENT wtf
For topological spaces
$\{X_\alpha\}_{\alpha \in I}$, let
{{c1::\[f : Y \rightarrow \prod_{\alpha \in I} X_\alpha.\]}}
For $\alpha \in I$, let
{{c1::\[f_\alpha : Y \rightarrow X_\alpha : y \mapsto \pi_\alpha\bigl(f(y)\bigr).\]}}
Then
{{c2::\[F : Y \rightarrow \prod_{\alpha \in I} X_\alpha : y \mapsto \bigl(f_\alpha(y)\bigr)_{\alpha \in I}.\]}}
is {{c2::continuous}}
iff {{c3::$\forall \alpha \in I$ : $f_\alpha$ is continuous}}.
**** Cloze
For topological spaces
$\{X_\alpha\}_{\alpha \in I}$ let
{{c1::$f$ : $Y \rightarrow \prod_{\alpha \in I} X_\alpha$}},
and for $\alpha \in I$ let
{{c1::$f_\alpha$ : $Y \rightarrow X_\alpha$ : $y \mapsto \pi_\alpha\bigl(f(y)\bigr)$}}.
Then {{c2::$f$ is continuous}}
iff {{c3::$\forall \alpha \in I$ : $f_\alpha$ is continuous}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
For topological spaces
$\{X_\alpha\}_{\alpha \in I}$, let
$f$ : $Y \rightarrow \prod_{\alpha \in I} X_\alpha$,
and for $\alpha \in I$ let
$f_\alpha$ : $Y \rightarrow X_\alpha$ : $y \mapsto \pi_\alpha\bigl(f(y)\bigr)$.

Prove that $f$ is continuous
iff $\forall \alpha \in I$ : $f_\alpha$ is continuous.
***** Back
Suppose $f$ is continuous.
Then, for $\alpha' \in I$ and an open set $U \subseteq X_{\alpha'}$,
\[f_{\alpha'}^{-1}(U) = f^{-1}\left(U \times \prod_{\alpha \in I \setminus \{\alpha'\}} X_\alpha\right)\]
is open as the preimage of a base cylinder set
in $\prod_{\alpha \in I} X_\alpha$.

Suppose $\forall \alpha \in I$ : $f_\alpha$ is continuous.
It suffices to verify that the preimage of $f$
for a base cylinder set $U$
is open.
Let $I' \subseteq I$ be a finite index subset for which
\[U = \prod_{\alpha \in I'} A_\alpha \times \prod_{\alpha \in I \setminus I'} X_\alpha.\]
Then
\[\begin{align*}
f^{-1}(U)
&= \left(\bigcap_{\alpha \in I'} f_{\alpha}^{-1}(A_\alpha)\right) \cap \left(\bigcap_{\alpha \in I \setminus I'} f_{\alpha}^{-1}(X_\alpha)\right) \\
&= \bigcap_{\alpha \in I'} f_{\alpha}^{-1}(A_\alpha)
\end{align*}\]
is open in $Y$
as the finite intersection of open sets in $Y$.
* 2024-01-12 Hilbert spaces & Hausdorff spaces
** inner product spaces
*** compactness in l_p
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
The closed unit ball in $l_p$ is not {{c1::compact}}
because {{c1::it contains $(x_n)_{n \in \mathbb{N} }$ where}}
{{c1::\[\forall n,k \in \mathbb{N} : \pi_k(x_n) = \begin{cases} 1 &k = n \\ 0 &k \neq n \end{cases},\]}}
{{c1::which has no convergent subsequence}}.
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
An {{c1::<<<inner product space>>>}} $V$ is a {{c2::normed vector space}}
with {{c1::an inner product operation}} {{c4::$\langle v,v' \rangle$}} for $v,v' \in V$
that induces its {{c3::norm}}

{{c3::$\|v\|^2$}} =: {{c4::$\langle v,v \rangle$}}.
*** parallelogram law
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
({{c2::Parallelogram law}}.)
{{c1::The norm}} in a vector space $V$ {{c1::is induced by an inner product}}
iff
{{c2::\[\forall v,v' \in V : \|v+v'\|^2 + \|v-v'\|^2 = 2\left(\|v\|^2 + \|v'\|^2\right)\]}}
holds.
**** Hanner's inequality
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
({{c3::Hanner's inequality}}.)
For a measure space $X$,
$p \in$ {{c1::$[1,\infty) \setminus \{2\}$}},
and $f,g \in L^p(X)$,
{{c2::\[\|f+g\|_p^p + \|f-g\|_p^p * \big( \|f\|_p + \|g\|_p \big)^p + \big| \|f\|_p-\|g\|_p \big|^p\]}}
where $*$ := {{c1::$\begin{cases} \ge &p < 2 \\ \le &p > 2 \end{cases}$}}.
If $p$ = {{c1::$2$}}, then this becomes {{c3::the parallelogram law}}.
*** Hilbert spaces
**** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
A {{c2::<<<Hilbert space>>>}} is a {{c1::complete}} {{c3::inner product space}}.
**** l_2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
{{c1::$l_2$}} is a {{c3::Hilbert}} space with

{{c2::$\bigl\langle (a_n)_{n \in \mathbb{N} }, (b_n)_{n \in \mathbb{N} } \bigr\rangle$}}
= {{c3::$\sum_{n \in \mathbb{N} } |a_n \overline{b_n}|$}}.
**** L^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For a measure space $X$,
{{c2::$L^2\bigl(X\bigr)$}} is a {{c3::Hilbert}} space with
$\langle f,g \rangle$ := {{c1::$\int_X f(x) \overline{g(x)} dx$}}.
***** Parseval's identity
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
({{c3::<<<Parseval>>>'s identity}}.)
For $f \in L^2\bigl([0,2\pi]\bigr)$,
which has a basis {{c4::$\{e^{inx}\}_{n \in \mathbb{Z} }$}},
{{c1::\[\begin{align*}\|f\|_2^2 &= \int_0^{2\pi} |f(x)|^2 dx \\ &= 2\pi \sum_{n \in \mathbb{Z} } \left|\hat{f}(n)\right|^2 = \langle f,f \rangle\end{align*}\]}}
where $\hat{f}(n)$ = {{c2::$\langle f, e^{inx} \rangle$}} = {{c2::$\frac{1}{2\pi} \int_0^{2\pi} f(x) e^{-inx} dx$}}.
**** compactness in a Hilbert space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
(Consequence of {{c3::Riesz's lemma}}.)
{{c1::The closed unit ball}} in a {{c4::Hilbert space}} $V$ is {{c1::compact}}
iff {{c2::$V$ is finite-dimensional}}.
** compact sets & continuity
\medskip
*** continuous image of a compact set is compact
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c2::Continuous}} functions map {{c1::compact sets}} to {{c3::compact sets}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that continuous functions map compact sets to compact sets.
***** Back
Let $f$ be continuous and $A$ a compact set in its domain.
The preimages of an open cover $U$ of $f(A)$
form an open cover $U'$ of $A$.
Then a finite subcover of $U'$ exists,
and the images of sets in $U'$
form a finite subcover of $U$.
*** Tychonoff's theorem
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
({{c3::<<<Tychonoff>>>}}.)
If {{c1::$\forall \alpha \in I$ : $X_\alpha$ is compact}},
then {{c2::$\prod_{\alpha \in I} X_\alpha$}} is {{c3::compact in the product topology}}.
*** homeomorphism
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For topological spaces $X$ and $Y$,
a {{c2::bijection}} $f$ : $X \rightarrow Y$
is {{c1::a homeomorphism}} iff
{{c2::$f$ and $f^{-1}$ are both continuous}}.
*** distance from a set is continuous
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a subset $A$ of a metric space $(X,d)$ and $x \in X$,
$d(x,A) := \inf_{x' \in A} d(x,x')$
is {{c1::continuous}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
For a subset $A$ of a metric space $(X,d)$ and $x \in X$,
prove that
\[d(x,A) := \inf_{x' \in A} d(x,x')\]
is continuous.
***** Back
Let $\epsilon,\delta > 0$.
Then
$\exists a \in A$ :
$d(x,A) +\delta$,
so for $x' \in B(x,\epsilon)$
\[\begin{align*}
d(x',A)
&\le d(x',a) \\
&\le d(x,a) + d(x,x') \\
&< d(x,A) + \delta + \epsilon.
\end{align*}\]
Taking the limit as $\delta \rightarrow 0$ gives
$d(x',A) \le d(x,A) + \epsilon$.
By parallel reasoning,
$d(x,A) \le d(x',A) + \epsilon$,
hence $|d(x,A) - d(x',A)| \le \epsilon$.
** Hausdorff spaces
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $(X,\tau)$ is
{{c1::a <<<Hausdorff space>>>}}
when {{c2::$\forall x \neq x' \in X$ : $\exists U, U' \in \tau$ : $\bigl[U \cap U'$ = $\emptyset \land (x,x') \in U \times U'\bigr]$}}.
*** metric spaces are Hausdorff spaces
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
All {{c1::metric spaces}} are Hausdorff spaces.
*** singletons are closed sets
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Singletons in {{c2::a Hausdorff space}} $X$
with topology $\tau$
are {{c1::closed}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that singletons in a Hausdorff space $(X,\tau)$ are closed.
***** Back
Let $x' \in X$. Then
\[\forall x \in X :
\exists U_x \in \tau :
\bigl[x \in U_x \land x' \notin U_x\bigr]
\implies X \setminus \{x'\}
= \bigcup_{x' \in X \setminus \{x'\}} U_x \in \tau.\]
*** trivial topology
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
$\tau$ := {{c1::$\{\emptyset,X\}$}} is {{c2::the <<<trivial topology>>> on $X$}}.
**** trivial topological are not Hausdorff spaces
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
If $\tau$ is {{c1::the trivial topology}} and
{{c2::$|X| > 1$}},
then $(X,\tau)$ is {{c3::not a Hausdorff space}}.
*** subspace topology
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
The {{c1::<<<subspace topology>>>}} on a subspace $Y$ of a topological space $(X,\tau)$
is $\tau_Y$ := {{c2::$\bigl\{U \cap Y \bigm| U \in \tau\bigr\}$}}.
**** subspaces of Hausdorff spaces are Hausdorff spaces
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
Any subspace of {{c3::a Hausdorff space}} is {{c2::a Hausdorff space}} under {{c1::the subspace topology}}.
*** product of Hausdorff spaces is a Hausdorff space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For Hausdorff spaces $(X,\tau)$ and $(X',\tau')$,
$X \times X'$ under the product topology
is {{c1::a Hausdorff space}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
For Hausdorff spaces $(X,\tau)$ and $(X',\tau')$,
prove that $X \times X'$ with the product topology
is a Hausdorff space.
***** Back
Let $\mathcal{B}$ be the cylinder set basis for the product topology
and let $(x_0,x'_0) \neq (x_1,x'_1) \in X \times Y$, assuming wlog that
$x_0 \neq x_1$. Then
\[\exists U_0,U_1 \in \tau :
\bigl[U_0 \cap U_1 = \emptyset \land (x_0,x_1) \in U_0 \times U_1\bigr],\]
so $U_0 \times X'$ and $U_1 \times X'$ are disjoint open sets that contain
$(x_0,x'_0)$ and $(x_1,x'_1)$ respectively.
*** compact subspace of a Hausdorff space is closed
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Any {{c1::compact}} subspace of a Hausdorff space is {{c2::closed}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that any compact subspace
of a Hausdorff space is closed.
***** Back
Let $(X,\tau)$ be a Hausdorff space,
$A \subseteq X$ a compact subset,
and $x' \in X \setminus A$.
For $x \in A$, let $U_x, U'_x \in \tau$ such that
$U_x \cap U'_x$ = $\emptyset$
and $(x,x') \in U_x \times U'_x$.

Since $\{U_x\}_{x \in A}$ is an open cover of $A$, let
$\{x_n\}_{n \in [m]} \subseteq A$
such that
$\{U_{x_n}\}_{n \in [m]}$
covers $A$.
Then $x' \in \bigcap_{n \in [m]} U'_{x_n} \subseteq X \setminus A$,
and this intersection is open and disjoint to $\bigcup_{n \in [m]} U_{x_n}$.
Thus $X \setminus A$ is open.
*** continuous bijections from a compact space to a Hausdorff space are homeomorphisms
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::continuous bijection}} $f$ : $X \rightarrow Y$ is {{c3::a homeomorphism}}
if $X$ is {{c2::compact}} and
$Y$ is {{c2::a Hausdorff space}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that a continuous bijection
$f$ : $X \rightarrow Y$ is a homeomorphism
if $X$ is compact and
$Y$ is a Hausdorff space.
***** Back
Let $A \subseteq X$ be closed.
Then $A$ is compact, so
$\left(f^{-1}\right)^{-1}(A) = f(A)$
is closed as a compact subset of a Hausdorff space.
It follows that $f^{-1}$ is continuous.
*** normal spaces
**** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
A {{c3::Hausdorff space}} $(X,\tau)$ is {{c2::a <<<normal>>> space}} when
{{c1::\[\exists U,U' \in \tau : \bigl[U \cap U \neq \emptyset \land A \subseteq U \land A' \subseteq U'\bigr]\]}}
for any {{c1::disjoint closed sets $A,A' \subseteq X$}}.
**** compact Hausdorff spaces are normal spaces
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
All {{c2::compact}} Hausdorff space are {{c1::normal spaces}}.
***** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
Prove that all compact Hausdorff spaces
are normal spaces.
****** Back
Let $(X,\tau)$ be a compact Hausdorff space and
$A,A' \subseteq X$ closed sets with
$A \cap A'$ = $\emptyset$.
For $x \in A$, let $U_x, U'_x \in \tau$ such that
$U_x \cap U'_x$ = $\emptyset$,
$x \in U_x$, and $A' \subseteq U'_x$.

Since $\{U_x\}_{x \in A}$ is an open cover of $A$
and $A$ is compact as the closed subset of a compact set,
let
$\{x_n\}_{n \in [m]} \subseteq A$
such that
$\{U_{x_n}\}_{n \in [m]}$
covers $A$.
It follows that $\bigcup_{n \in [m]} U_{x_n}$ and
$\bigcap_{n \in [m]} U'_{x_n} \supseteq A'$
are open and disjoint.
**** metric spaces are normal spaces
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
All {{c1::metric spaces}} are normal spaces.
***** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
Prove that all metric spaces are normal spaces.
****** Back
Let $A,A' \subseteq X$ be disjoint and closed.
Then
\[U_A := \bigl\{x \mid d(x,A) < d(x,A')\bigr\},
\qquad U_A' := \bigl\{x \mid d(x,A') < d(x,A)\bigr\},
\qquad\]
are disjoint,
and they are respective open supersets of $A$ and $A'$ because
$x \in A \implies d(x,A) = 0 < d(x,A')$ (and vice versa) and
\[U_A = f^{-1}\bigl((-\infty,0)\bigr),
\qquad U_A' = f^{-1}\bigl((0,\infty)\bigr)\]
where $f$ : $x \mapsto d(x,A) - d(x,A')$ is continuous as the difference between continuous functions.
** Lebesgue number
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::<<<Lebesgue number>>>}} of
{{c2::an open cover $\{A_\alpha\}_{\alpha \in I}$ of $X$}}
is {{c3::$\epsilon > 0$ such that $\forall x \in X$ : $\exists \alpha \in I$ : $B(x,\epsilon) \subseteq A_\alpha$}}.
*** open covers of compact metric spaces have a Lebesgue number
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Any open cover of {{c1::a compact metric space}} has {{c2::a Lebesgue number}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that any open cover of a compact metric space has a Lebesgue number.
***** Back
Let $X$ be a compact metric space
and $\{U_\alpha\}_{\alpha \in I}$ an open cover of $X$
with finite subcover $\{U_{\alpha_n}\}_{n \in [m]}$.
For $n \in [m]$ and $x \in X$, let
\[d_n(x) := d(x, X \setminus U_n),\]
noting that $B(x,\epsilon) \subseteq U_n$
$\iff d_n(x) \ge \epsilon$
and that $\exists n \in [m] : x \in U_n \implies d_n(x) > 0$.

Let $f(x)$ := $\max_{n \in [m]} d_n(x)$,
which is continuous as the maximum of continuous functions.
Then $f(X) \subseteq (0,\infty)$
is compact hence closed and bounded.
It follows that
$\exists \delta > 0$ : $f(X) \subseteq [\delta,\infty)$
and $\delta$ is a Lebesgue number for $\{U_\alpha\}_{\alpha \in I}$.
*** continuous functions on compact metric spaces are uniformly continuous
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $f$ : $X \rightarrow Y$ is {{c1::continuous}},
$X$ and $Y$ are metric spaces,
and $X$ is {{c1::compact}}, then
$f$ is {{c2::uniformly continuous}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
If $f$ : $X \rightarrow Y$ is continuous,
$X$ and $Y$ are metric spaces,
and $X$ is compact, prove that
$f$ is uniformly continuous.
***** Back
For $\epsilon > 0$,
let $\delta$ be a Lebesgue number for
$\bigl\{f^{-1}\bigl(B(y, \epsilon)\bigr)\bigr\}_{y \in Y}$.
Then $\forall x \in X$ :
$\exists y \in Y : f\bigl(B(x,\delta)\bigr) = B(y, \epsilon)$,
so for $x' \in B(x,\delta)$
\[\begin{align*}
d\bigl(f(x),f(x')\bigr) &\le \\
d\bigl(f(x),y\bigr) + d\bigl(f(x'),y\bigr)
&< 2 \epsilon.
\end{align*}\]
* 2024-01-17 product spaces & separable spaces
** metrizability
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $(X,\tau)$ is {{c1::<<<metrizable>>>}} when
{{c2::there exists a metric $d$ on $X$ that induces $\tau$}}.
In other words, {{c2::the set of open balls with respect to $d$ is a basis for $\tau$}}.
*** metrizable spaces are normal
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Any topological space that is not {{c1::normal}} is non-metrizable.
*** countable product of metric spaces is metrizable
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $\forall n \in \mathbb{N}$ :
$(X_n,d_n)$ are {{c1::metric spaces}},
then $X$ := {{c2::$\prod_{n \in \mathbb{N} } X_n$}} is
{{c3::metrizable under the product topology}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
If $\forall n \in \mathbb{N}$ :
$(X_n,d_n)$ are metric spaces,
prove that $X$ := $\prod_{n \in \mathbb{N}} X_n$ is
metrizable under the product topology.
***** Back
For $n \in \mathbb{N}$ and $x_n,  y_n \in X_n$ let
$\tilde{d}(x_n,y_n)$ :=
$\frac{d_n(x_n,y_n)}{1 + d_n(x_n,y_n)} \le 1$,
noting that this is an equivalent metric to $d_n$.
Then define
\[D :
X \rightarrow \mathbb{R} :
(x_n)_{n \in \mathbb{N}}, (y_n)_{n \in \mathbb{N}} \mapsto \sum_{n \in \mathbb{N}} \left(\frac{\tilde{d}_n(x_n,y_n)}{2^n}\right).\]
As shown in problem set 1,
$D$ induces the product topology on $X$.
** countable product of compact metric spaces
*** discrete topology
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
$\tau$ := {{c1::$\mathcal{P}(X)$}} is {{c2::the discrete topology on $X$}}.
**** compact product counterexample
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
$X$ := $\prod_{n \in \mathbb{N}} \{0,1\}$ is not compact under {{c2::the discrete topology}}
because {{c3::the set of singletons in $X$ is an open cover of $X$ with no finite subcover}}.
*** countable Tychonoff
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
({{c1::Tychonoff for countable products}}.)
If {{c4::$\forall n \in \mathbb{N}$ : $(X_n,\tau_n)$ is a compact topological space}},
then $X$ := {{c2::$\prod_{n \in \mathbb{N} } X_\alpha$}} is {{c3::compact under the product topology}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
(Tychonoff for countable products.)
If $\forall n \in \mathbb{N}$ : $X_n$ is compact,
prove that $X$ := $\prod_{n \in \mathbb{N}} X_\alpha$ is compact under the product topology $\tau$.
***** Back
Suppose $X$ is not compact and let
$C$ := $\{C_\alpha\}_{\alpha \in I}$ be an open cover of $X$ with no finite subcover.

Suppose for every $x_0 \in X_0$ that there is a set $U_{x_0} \in \tau_0$ such that
\[x_0 \in U_{x_0} \land \exists I' \subseteq I :
\left[|I'| \in \mathbb{N} \land
\left(U_{x_0} \times \prod_{n \in \mathbb{Z}_+} X_n\right) \subseteq \bigcup_{\alpha \in I'} C_\alpha.\right]\]
Then
\[X \subseteq \bigcup_{x_0 \in X_0} \left(U_{x_0} \times \prod_{n \in \mathbb{Z}_+} X_n\right).\]
Since $X_0$ is compact, this open cover has a finite subcover
and contradicts that $C$ has no finite subcover.
Thus there is some $x_0 \in X_0$ for which no such $U_{x_0}$ exists.

By similar reasoning, there exists $x_1 \in X_1$ such that no cylinder set of the form
$U_{x_0} \times U_{x_1} \times \prod_{n \in \mathbb{Z}_+ \setminus \{1\}} X_n$
both satisfies $(x_0,x_1) \in U_{x_0} \times U_{x_1}$
and has a finite open cover in $C$; otherwise,
\[\left(U_{x_0} \times \prod_{n \in \mathbb{Z}_+} X_n\right) \subseteq \bigcup_{x_1 \in X_1} \left(U_{x_0} \times U_{x_1} \times \prod_{n \in \mathbb{Z}_+ \setminus \{1\}} X_n\right)\]
would have a finite subcover by compactness of $X_1$
and thus $\left(U_{x_0} \times \prod_{n \in \mathbb{Z}_+} X_n\right)$ would have a finite open cover in $C$.

Selecting $x_n \in X_n$ in this fashion for every $n \in \mathbb{N}$
provides a point $x$ := $(x_n)_{n \in \mathbb{N}} \in X$ such that,
for any $m \in \mathbb{N}$,
every cylinder set of the form
\[\prod_{n=0}^m U_n \times \prod_{n=m+1}^\infty X_n,\]
where $(x_n)_{n=0}^m \in \prod_{n=0}^m U_n$,
has no finite open cover in $C$.
But this cannot be;
$\exists C_\alpha \in C$ : $x \in C_\alpha$,
implying that $x$ lies in some cylinder set
$V := \prod_{n \in \mathbb{N}} V_n \subseteq C_\alpha$
in the product topology basis.
Taking $m$ to be the maximum index $n$ for which $V_n \neq X_n$ gives
\[(x_n)_{n \in \mathbb{N}} \in \left(\prod_{n=0}^m V_n \times \prod_{n=m+1}^\infty X_n\right) \subseteq C_\alpha,\]
which is certainly a finite cover.
** separability
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::metric space}} is {{c2::<<<separable>>>}} when
{{c3::it has a countable dense subset}}.
*** compact metric spaces are separable
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
All {{c1::compact}} metric spaces are separable.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that all compact metric spaces are separable.
***** Back
Let $X$ be a compact metric space.
For $n \in \mathbb{Z}_+$,
$X \subseteq \bigcup_{x \in X} B\left(x, \frac{1}{n}\right)$,
and by compactness, let $N_n \subseteq X$ be a finite subset such that
$X \subseteq \bigcup_{x \in N_n} B\left(x, \frac{1}{n}\right)$.
Thus $\bigcup_{n \in \mathbb{Z}_+} N_n \subseteq X$ is dense and countable as the countable union of finite sets.
*** metric spaces with countable basis are separable
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A metric space $X$ with topology $\tau$ is {{c1::separable}} iff
{{c2::$\exists \{U_n\}_{n \in \mathbb{N} } \subseteq \tau$ : $\forall U \in \tau$ : $\exists N \subseteq \mathbb{N}$ : $U = \bigcup_{n \in N} U_n$}};
in other words, {{c2::$\tau$ has a countable basis}}.
*** subspaces of separable spaces are separable
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Any {{c2::subspace}} of a separable metric space is {{c1::separable}}.
*** examples of separable spaces
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c1::$\mathbb{R}^n$}}, {{c1::$C([a,b])$}}, and {{c1::$L^p([a,b])$ for $p \in [1,\infty)$}}
are examples of separable spaces.
*** example of a non-separable space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c2::$L^{\infty}([a,b])$}} is an example of a {{c1::non-separable}} space.
* 2024-01-19 boundedness & sequences of functions
** total boundedness
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A metric space $X$ is {{c1::<<<totally bounded>>>}} when
{{c2::$\forall \epsilon > 0$ : $\exists X' \subseteq X$ : $|X'| \in \mathbb{N} \land X \subseteq \bigcup_{x \in X'} B(x,\epsilon)$}}.
*** Cantor Intersection Theorem
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
({{c3::Cantor Intersection Theorem}}.)
A metric space $X$ is {{c2::complete}} iff
every collection
$\{A_n\}_{n \in \mathbb{N}}$
of {{c3::nonempty closed subsets of $X$}} such that
{{c3::\[\forall n \in \mathbb{N} : A_n \subseteq A_{n+1} \quad\text{and}\quad \lim_{n \rightarrow \infty} \text{diam} (A_n) = 0\]}}
satisfies
{{c1::$\exists x \in X$ : $\bigcap_{n \in \mathbb{N} } A_n = \{x\}$}}.
**** COMMENT TODO
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_FAILURE_REASON: cannot create note because it is empty
:END:
***** Front
***** Back
*** equivalent conditions to compactness
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A metric space $X$ is (1) {{c3::complete and totally bounded}} $\iff$
(2) $X$ is {{c1::compact}} $\iff$
(3) $X$ is {{c2::sequentially compact}}.
**** COMMENT TODO
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
Prove that a metric space $X$ is (1) complete and totally bounded $\iff$
(2) $X$ is compact $\iff$
(3) $X$ is sequentially compact.
***** Back
($1 \implies 2$.)
Suppose $X$ is complete and totally bounded.
Let $U$ := $\{U_\alpha\}_{\alpha \in I}$ be
an open cover of $X$ with no finite subcover.

Let $X_0 \subseteq X$ be a finite set such that
$X \subseteq \bigcup_{x \in X_0} B(x, 1)$.
Then there is some $x_0 \in X_0$
for which $B(x_0,1)$ has no finite cover in $U$; let $B_0$ be its closure.

For $n \in \mathbb{Z}_+$,
let $X_n \subseteq X$ be a finite set such that
$X \subseteq \bigcup_{x \in X_n} B\left(x,2^{-n}\right)$,
select $x_n \in X_n$ so that
$B_{n-1} \cap B\left(x_n,2^{-n}\right)$
has no finite cover in $U$,
and let $B_n$ be the closure of that intersection,
which has $\text{diam} (B_n) \le 2^{1-n}$.

Since
$\forall n \in \mathbb{N}$ : $B_n \subseteq B_{n+1}$,
and $\lim_{n \in \mathbb{N}} \text{diam} (B_n)$ = $0$,
it follows by the Cantor Intersection Theorem that
$\exists b \in X$ :
$\bigcap_{n \in \mathbb{N}} B_n = \{b\}$
Thus $\exists U_b \in U$ : $b \in U_b \implies$
$\bigl[\exists \epsilon > 0$ :
$B(b,\epsilon) \subseteq U_b\bigr]$.
But then $\exists n \in \mathbb{N}$ : $B_n \subseteq B(b,\epsilon) \subseteq U_b$,
which contradicts that $B_n$ has no finite cover in $U$ by construction.
Hence $X$ is compact.
** continuous functions on a compact metric space
*** normed vector space of continuous functions on a compact metric space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a {{c5::compact metric space}} $X$,

{{c1::$C(X)$}} := {{c2::$\bigl\{f : X \rightarrow \mathbb{R} \mid f \text{ is continuous}\bigr\}$}}

is a normed vector space with

{{c4::$\|f\|_\infty$}} := {{c3::$\max_{x \in X} |f(x)|$}}.
*** continuous functions on a compact metric space are complete
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If a metric space $(X,d)$ is {{c2::compact}},
then {{c1::$\bigl(C(X),||\cdot||_\infty\bigr)$}} is {{c3::complete}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
If a metric space $(X,d)$ is compact,
prove that $\bigl(C(X),||\cdot||_\infty\bigr)$ is complete.
***** Back
Let $(f_n)_{n \in \mathbb{N}}$ be
a Cauchy sequence in $C(X)$
and let $(f_{n_k})_{k \in \mathbb{N}}$ be a subsequence such that
$\forall k \in \mathbb{N}$ :
$\left\|f_{n_{k+1}} - f_{n_k}\right\|_\infty \le 2^{k}$.
For $x \in X$ and $j,k \in \mathbb{N}$,
\[\left|f_{n_{k+j}}(x) - f_{n_k}(x)\right| \le
\left\|f_{n_{k+j}} - f_{n_k}\right\|_\infty \le
\sum_{i=k}^{k+j-1} \left\|f_{n_{i+1}} - f_{n_i}\right\|_\infty
\le \sum_{i=k}^\infty 2^i,\]
hence $\bigl(f_{n_k}(x)\bigr)$ is a Cauchy sequence and converges in $\mathbb{R}$.
Let $f$ be the pointwise limit of
$\bigl(f_{n_k}(x)\bigr)_{k \in \mathbb{N}}$.
Taking the limit of the previous inequality
as $j \rightarrow \infty$ gives
\[\forall k \in \mathbb{N} :
\left\|f - f_{n_k}\right\|_\infty =
\max_{x \in X} \left|f(x) - f_{n_k}(x)\right| \le
\sum_{i=k}^\infty 2^i,\]
so the convergence is uniform.
Thus $(f_n)_{n \in \mathbb{N}}$ is a Cauchy sequence with a convergent subsequence in $C(X)$
and itself converges.
** boundedness of sets of functions
*** pointwise boundedness
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $X$ is a {{c3::metric space}}
and $\forall n \in \mathbb{N}$ :
$f_n$ : $X \rightarrow \mathbb{R}$,
then {{c3::$\{f_n\}_{n \in \mathbb{N}}$}}
is {{c2::<<<pointwise bounded>>>}} when
{{c1::$\forall x \in X$ : $\bigl\{f_n(x)\bigr\}_{n \in \mathbb{N} } \subseteq \mathbb{R}$ is a bounded set}}.
*** uniform boundedness
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $X$ is a {{c3::metric space}}
and $\forall n \in \mathbb{N}$ :
$f_n$ : $X \rightarrow \mathbb{R}$,
then {{c3::$\{f_n\}_{n \in \mathbb{N}}$}}
is {{c2::<<<uniformly bounded>>>}} when
{{c1::$\exists m > 0$ : $\forall (x,n) \in X \times \mathbb{N}$ : $|f_n(x)| \le m$}}.
** equicontinuity
*** equicontinuity at a point
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A set $\mathcal{F}$ of {{c3::real-valued functions on a metric space $X$}} is
{{c1::<<<equicontinuous>>>}} at $x \in X$ when
{{c2::$\forall \epsilon > 0$ : $\exists \delta > 0$ : $\forall f \in \mathcal{F}$ : $\forall x' \in X$ : $d(x,x') < \delta \implies |f(x) - f(x')| < \epsilon$}}.
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A set $\mathcal{F}$ of {{c3::real-valued functions on a topological space $X$}} is
{{c1::<<<pointwise equicontinuous>>>}}, or simply {{c1::equicontinuous}}, when
{{c2::$\forall x \in X$ : $\mathcal{F}$ is equicontinuous at $x$}}.
*** finite sets of continuous functions are equicontinuous
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Every {{c1::finite}} set of {{c1::continuous}} functions is {{c2::equicontinuous}}.
*** functions on an interval with uniformly bounded derivatives are equicontinuous
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For $a,b,m \in \mathbb{R}_+$ such that $a < b$,
{{c1::\[\Bigl\{f \in C([a,b]) \Bigm| \forall x \in [a,b] : \left|f'(x)\right| \le m\Bigr\}\]}}
is {{c2::equicontinuous}} by {{c3::the Mean Value Theorem}}, since
{{c3::\[\left|f(x)-f(x')\right| \le \left|x-x'\right| \sup_{t \in [x,x']} \left|f'(t)\right| \le \left|x-x'\right|m < \epsilon\]}}
for {{c3::$x,x' \in [a,b]$ such that $x<x' \land |x-x'| < \frac{\epsilon}{m}$}}.
*** Arzelà--Ascoli lemma
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
(Arzelà--Ascoli lemma.)
If a metric space $(X,d)$ is {{c1::separable}}
and $(f_n)_{n \in \mathbb{N} }$
is {{c1::an equicontinuous and pointwise bounded sequence of functions in $C(X)$}}, then
{{c2::a subsequence of $(f_n)_{n \in \mathbb{N} }$ converges pointwise to
some function $f$ : $X \rightarrow \mathbb{R}$}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
(Arzelà--Ascoli lemma.)
If a metric space $(X,d)$ is separable
and $(f_n)_{n \in \mathbb{N} }$
is an equicontinuous and pointwise bounded sequence of functions in $C(X)$, prove that
a subsequence of $(f_n)_{n \in \mathbb{N} }$
converges pointwise to
some function $f$ : $X \rightarrow \mathbb{R}$.
***** Back
Let $X'$ := $\{x_k\}_{k \in \mathbb{N}} \subseteq X$ be dense in $X$.
Since $\bigl\{f_n(x_0)\bigr\}_{n \in \mathbb{N}} \subseteq \mathbb{R}$ is bounded,
$\bigr(f_n(x_0)\bigr)_{n \in \mathbb{N}}$ has a convergent subsequence.
Let $(n_{0,i})_{i \in \mathbb{N}}$ be a sequence of indices that defines such a subsequence,
and let $l_0$ := $\lim_{i \rightarrow \infty} f_{n_{0,i}}(x_0)$.

For $k \in \mathbb{Z}_+$,
let $(n_{k,i})_{i \in \mathbb{N}}$ be a subsequence of $(n_{k-1,i})_{i \in \mathbb{N}}$ such that
$f_{n_{k,i}}(x_k) \rightarrow l_k$.
This is always possible because $\bigr(f_{n_{k-1,i}}(x_k)\bigr)_{i \in \mathbb{N}}$ is bounded and thus has a convergent subsequence.
To avoid producing an ``empty'' sequence from this infinite construction,
take the diagonal sequence
$(n_{i,i})_{i \in \mathbb{N}}$
and let
\[f(x_k) := l_k = \lim_{i \rightarrow \infty} f_{n_{i,i}}\]
for $k \in \mathbb{N}$.
Then $f$ is the pointwise limit of $\bigl\{f_{n_{i,i}}\bigr\}$ in $X'$.

Now let $x \in X$ and $\epsilon > 0$.
Since $\{f_n\}_{n \in \mathbb{N}}$ is equicontinuous,
$\exists \delta > 0$ :
$\forall n \in \mathbb{N}$ :
$\forall x' \in X$ :
$d(x,x') < \delta \implies |f_n(x) - f_n(x')| < \epsilon$,
and since $X'$ is dense
$\exists x' \in X'$ : $d(x,x') < \delta$.
Let $m \in \mathbb{N}$ such that
\[\forall i \ge j \ge m : \left|f_{n_{i,i}}(x') - f_{n_{j,j}}(x')\right| < \frac{\epsilon}{3}.\]
By the triangle inequality,
\[\begin{align*}
\forall i \ge j \ge m : \left|f_{n_{i,i}}(x) - f_{n_{j,j}}(x)\right|
&\le \left|f_{n_{i,i}}(x) - f_{n_{i,i}}(x')\right| \\
&+ \left|f_{n_{i,i}}(x') - f_{n_{j,j}}(x')\right| \\
&+ \left|f_{n_{j,j}}(x') - f_{n_{j,j}}(x)\right|
< 3 \cdot \frac{\epsilon}{3}.
\end{align*}\]
It follows that $\bigl(f_{n_{i,i}}(x)\bigr)_{i \in \mathbb{N}}$
is a Cauchy sequence in $\mathbb{R}$, so it converges;
setting $f(x)$ to its limit
makes $f$ converge pointwise in $X$.
* COMMENT 2024-01-24
** Arzelà--Ascoli theorem
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
*** Cloze
(Arzelà--Ascoli theorem.)
If a metric space $(X,d)$ is compact and separable
and $(f_n)_{n \in \mathbb{N} }$
is an equicontinuous and uniformly bounded sequence of functions in $C(X)$, then
a subsequence of $(f_n)_{n \in \mathbb{N} }$
converges uniformly to some function $f \in C(X)$.
*** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
(Arzelà--Ascoli theorem.)
If a metric space $(X,d)$ is compact and separable
and $(f_n)_{n \in \mathbb{N} }$
is an equicontinuous and uniformly bounded sequence of functions in $C(X)$, prove that
a subsequence of $(f_n)_{n \in \mathbb{N} }$
converges uniformly to some function $f \in C(X)$.
**** Back
