# -*- after-save-hook: (lambda () (org-latex-export-to-pdf t)) org-export-before-parsing-hook: (org-export-before-parsing-mathnotes) -*-
#+LATEX_CLASS: mathnotes
#+TITLE: MATH 455 (Honours Analysis 4)
#+AUTHOR: J. Han
#+PROPERTY: ANKI_DECK /edu/math/455/

* preamble

The following notes are adapted from lectures given by Dmitry Jakobson in Winter 2024.
All errors in interpretation, reasoning, coherence, and articulation are my own.

This document's source code, located at https://github.com/brunefig/math455/blob/main/notes.org,
can be converted into [[https://apps.ankiweb.net/][Anki]] flashcards with the [[https://github.com/louietan/anki-editor/][\texttt{anki-editor}]] package for [[https://www.gnu.org/software/emacs/][GNU Emacs]].
Flashcard [[https://en.wikipedia.org/wiki/Cloze_test][cloze deletions]] are typeset in {{c1::magenta}}.

* 2024-01-05 topology & metric spaces
** connectedness
*** connected space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ is {{c1::a <<<connected space>>>}} iff
there are no {{c2::open}} sets $U,U' \in$
{{c3::$\mathcal{P}(X) \setminus \{\emptyset\}$}} such that
{{c3::$U \cap U'$ = $\emptyset$}}
and {{c3::$X$ = $U \cup U'$}}.
*** connected set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a topological space $X$,
$A \subseteq X$ is {{c1::a <<<connected>>> set}} iff
there are no {{c2::open}} sets $U,U' \subseteq X$ such that
{{c3::$A \cap U \neq \emptyset$}},
{{c3::$A \cap U' \neq \emptyset$}},
{{c3::$U \cap U'$ = $\emptyset$}},
and {{c3::$A$ = $(U \cap A) \cup (U' \cap A)$}}.
*** path connectedness
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ is {{c1::a <<<path connected>>> space}} iff
{{c2::$\forall x,x' \in X$ :
$\exists$ continuous $f : [0,1] \rightarrow X$ :
$[f(0)$ = $x$
$\land$
$f(1)$ = $x']$}}.
**** path connected implies connected
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
{{c2::All}} path connected spaces are {{c1::connected spaces}}.
**** connectedness is equivalent to path connectedness in R^n
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For {{c1::open}} sets in {{c1::$\mathbb{R}^n$}},
{{c2::connectedness}} is equivalent to {{c3::path connectedness}}.
*** connected components
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ can be expressed as
{{c1::the disjoint union of maximal connected subsets}},
where a connected subset is called maximal iff
{{c1::it has no connected superset in $X$}}.
These subsets are the {{c2::<<<connected components>>>}} of $X$.
**** path components
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
A topological space $X$ can be expressed as
{{c1::the disjoint union of maximal path connected subsets}},
where a path connected subset is called maximal iff
{{c1::it has no path connected superset in $X$}}.
These subsets are the {{c2::<<<path components>>>}} of $X$.
***** path connected spaces have one path component
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
A {{c1::path connected}} space has exactly one {{c2::path component}}.
***** connected does not imply path connected
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
{{c1::$\Bigl\{\Bigl(x,\sin\left(\frac{1}{x}\right)\Bigr) \Bigm| x \in (0,1]\,\Bigr\} \cup \{(0,0)\}$}}
$\subseteq \mathbb{R}^2$ is
{{c2::connected}} but not {{c2::path connected}}
because {{c3::it has two path components}}.
*** continuous image of a connected set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $f$ : $X \rightarrow \mathbb{R}$ is continuous,
$A \subseteq X$ is connected, and
$x,x' \in f(A)$
such that $x < x'$,
then {{c1::$[x,x'] \subseteq f(A)$}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
If $f$ : $X \rightarrow \mathbb{R}$ is continuous,
$A \subseteq X$ is connected, and
$x,x' \in f(A)$
such that $x < x'$, prove that

$[x,x'] \subseteq f(A)$.
***** Back
Suppose $\exists c \in \bigl(f(x'),f(x)\bigr)$ : $c \notin f(A)$.
Since
$f^{-1}\bigl((-\infty,c)\bigr)$
and
$f^{-1}\bigl((c,\infty)\bigr)$
are open,
$A \subseteq f^{-1}\bigl((-\infty,c)\bigr) \cup f^{-1}\bigl((c,\infty)\bigr)$
is not connected.
** examples of metric spaces
*** induced metric for a normed vector space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
Any normed vector space is a metric space with the induced metric

$d(x,x')$ := {{c1::$||x-x'||$}}.
*** l_p
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For $p \in$ {{c1::$(0,\infty)$}},

{{c2::$l_p$}} :=
{{c3::$\left\{(x_n)_{n \in \mathbb{N} } \in \mathbb{C}^{\mathbb{N} } \,\middle| \sum_{n \in \mathbb{N} } |x_n|^p < \infty\right\}$}}

is a normed vector space with

$||x||_p$ :=
{{c3::$\bigl(\sum_{n \in \mathbb{N} } |x_n|^p\bigr)^{1/p}$}}.
**** 1/n sequence
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
The sequence $\left(\frac{1}{n}\right)_{n \in \mathbb{Z}_+}$
is a member of $l_p$
iff {{c1::$p > 1$}}.
***** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
****** Front
Prove that
$\left(\frac{1}{n}\right)_{n \in \mathbb{Z}_+} \in l_p$
iff $p > 1$.
****** Back
$\left(\frac{1}{n}\right)_{n \in \mathbb{Z}_+} \in l_p$
$\iff$
$\sum_{n \in \mathbb{Z}_+} \left(\frac{1}{n}\right)^p < \infty$
$\iff$
$p > 1$.
*** L_p
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For $p \in$ {{c1::$[1,\infty)$}},

{{c2::$L^p([a,b])$}} :=
{{c3::$\left\{f(x) \,\middle| \int_a^b |f(x)|^p dx < \infty\right\}$}}

is a normed vector space with

$||f||_p$ :=
{{c3::$\left(\int_a^b |f(x)|^p dx\right)^{1/p}$}}.
*** symmetric difference metric
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
$d(A,A')$ :=
$\text{vol}_n(A \triangle A')$
is a possible metric on {{c1::$\mathbb{R}^n$}}.
*** Hausdorff
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a metric space $(X,d)$,
a set $A \subseteq X$,
and $\epsilon > 0$,
let $A_\epsilon$ :=
{{c1::$\bigcup_{x \in A} B(x,\epsilon)$}}.
Then the {{c2::<<<Hausdorff>>>}} metric is

{{c2::$d_H(A,A')$}} := {{c3::$\inf \bigl\{\,\epsilon > 0 \bigm| A' \subseteq A_\epsilon \land A \subseteq A'_\epsilon\bigr\}$}}.
*** $p\text{-adic}$ numbers
**** normed vector space of rational numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
Given a fixed prime $p$,
{{c1::\[\forall q \in \mathbb{Q} \setminus \{0\} : \exists (a,b,n) \in \mathbb{Z}^3 : \left[\,q = p^n \cdot \frac{a}{b} \land\, \gcd(a,p) = \gcd(b,p) = 1\,\right]\]}}
and {{c2::$\mathbb{Q}$}} is a normed vector space with

$||q||_p$ := {{c3::$\begin{cases} p^{-n} & q \neq 0 \\ 0 & q = 0 \end{cases}$}}.
***** p = 2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The 2-adic norm of $\frac{96}{7}$ is
{{c1::$\frac{1}{32}$}}.
***** p = 3
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The 3-adic norm of $3^{-2024} \cdot \frac{8}{13}$ is
{{c1::$3^{2024}$}}.
***** intuition for the p-adic norm
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The {{c3::$p\text{-adic}$}} norm
$||q||_p$ is {{c1::small}}
if $q$ is {{c2::divisible by a large power of $p$}}.
***** intuition for the p-adic norm of zero
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
****** Cloze
The $p\text{-adic}$ norm of $0$ is $0$ because
{{c1::$0$ is divisible by any power of $p$}}.
**** COMMENT completion of Q wrt the p-adic norm
~= Laurent series in powers of p with finitely many negative powers of p
extend Taylor series into negative powers
a_{-k} p^{-k} + a_{-k+1} p^{-k+1} + \dots + a_0 + a_1 p + a_2 p^2 + \dots + a_n p^n + \dots
where $a_i \in \{\0,\dots,p-1}$ are remainders mod p

what are the 2-adic series expansions of 12 and 1/3?
if 12 is a p-adic integer then its series begins at a positive index (in this case 2)
but then 1/3 has infinitely many negative power terms??????????

***** p-adic rationals
\lim ||x||_p = ||a_n p^n + a_{n+1} p^{n+1} + \dots||_p \rightarrow 0
this set of Laurent series is $\mathbb{Q}_p$, the p-adic rational numbers
**** product formula for /p/-adic norms of rational numbers
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
(/p/-adic product formula.)
If $q \in$ {{c1::$\mathbb{Q} \setminus \{0\}$}}, then
{{c2::$|q| \cdot \prod_{p \text{ prime} } ||q||_p$}} = {{c3::$1$}}.
**** COMMENT difference between mathematicians, physicists, and engineers
math: 9 is a counterexample
physicists: 9 is an experimental error
engineer: 9 is prime
** convexness
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A set $X$ is {{c1::<<<convex>>>}} iff
{{c2::the line segment joining any two points in $X$ lies within $X$}}.
* 2024-01-10 contraction mappings & product topologies
$\alpha \in I$ henceforth refers to members of a possibly uncountable index set $I$.
** arbitrary union of intersecting connected sets is connected
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
*** Cloze
If $\{A_\alpha\}_{\alpha \in I}$ is a family of {{c1::connected}} sets
such that $\forall \alpha,\alpha' \in I$ :
{{c2::$A_\alpha \cap A_{\alpha'} \neq \emptyset$}},
then {{c3::$\bigcup_{\alpha \in I} A_\alpha$}} is {{c4::connected}}.
*** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
**** Front
If $\{A_\alpha\}_{\alpha \in I}$ is a family of connected sets in $X$
such that $\forall \alpha,\alpha' \in I$ :
$A_\alpha \cap A_{\alpha'} \neq \emptyset$,
prove that $\bigcup_{\alpha \in I} A_\alpha$ is connected.
**** Back
Suppose $A$ := $\bigcup_{\alpha \in I} A_\alpha$ is not connected.
Let $U,U' \subseteq X$ be open and nonempty relative to $A$
such that $U \cap U'$ = $\emptyset$ and $A$ = $U \cup U'$.
Since each $A_\alpha$ is connected, there is no $\alpha$ for which
$A_\alpha \cap U \neq \emptyset \neq A_\alpha \cap U'$.
But then $\exists \alpha,\alpha' \in I$ : $A_\alpha \subseteq U \land A_{\alpha'} \subseteq U'$,
which contradicts that $A_\alpha \cap A_{\alpha'} \neq \emptyset$.
** total disconnectedness
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A topological space $X$ is {{c1::totally disconnected}}
iff {{c2::every connected subset of $X$ is a singleton}}.
*** totally disconnected subspaces of R
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::totally disconnected}} space in $\mathbb{R}$
contains {{c3::only}} {{c2::points}} and {{c3::no}} {{c2::intervals}}.
*** Cantor set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c1::The Cantor set}} is a totally disconnected space in $\mathbb{R}$.
** contraction mappings
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a metric space $(X,d)$,
$T$ : {{c1::$X$}} $\rightarrow$ {{c1::$X$}}
is {{c2::a contraction mapping}} iff
{{c3::$\exists c \in [0,1)$ : $\forall x,x' \in X$ :
$d\bigl(T(x),T(x')\bigr) \le c \cdot d(x,x')$}}.
*** contraction mappings are continuous
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
All contraction mappings are {{c1::continuous}}.
*** orbit of a contraction mapping is a Cauchy sequence
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
(<<<Orbit lemma>>>.)
For $x \in X$, the {{c1::orbit}} {{c2::$\bigl(T^n(x)\bigr)_{n \in \mathbb{N} }$}}
of a {{c3::contraction mapping}} $T$ on $X$
is {{c4::a Cauchy sequence}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
(Orbit lemma.)
For $x \in X$, prove that the orbit
$\bigl(T^n(x)\bigr)_{n \in \mathbb{N}}$
of a contraction mapping $T$ on $X$
is a Cauchy sequence.
***** Back
For $n \in \mathbb{Z}_+$,
\[\begin{align*}
d\left(T^n(x),T^{n+1}(x)\right)
&< c \cdot d\left(T^{n-1}(x),T^n(x)\right) \\
&< c^2 \cdot d\left(T^{n-2}(x),T^{n-1}(x)\right) \\
\cdots &< c^n \cdot d\bigl(x,T(x)\bigr).
\end{align*}\]
Let $m \ge n$.
By the triangle inequality,
\[\begin{align*}
d\left(T^n(x),T^m(x)\right)
&\le \sum_{k=n}^{m-1} d\left(T^k(x),T^{k+1}(x)\right) \\
&\le d\bigl(x,T(x)\bigr) \sum_{k=n}^{m-1} c^k \\
&= c^n \cdot d\bigl(x,T(x)\bigr) \sum_{k=0}^{m-n-1} c^k \\
&\le \frac{c^n \cdot d\bigl(x,T(x)\bigr)}{1-c}.
\end{align*}\]
For $\epsilon > 0$, choosing
$n > \log_c \left(\frac{\epsilon}{2} \cdot \frac{1-c}{d\bigl(x,T(x)\bigr)}\right)$
and $m,m' \ge n$ guarantees
\[\begin{align*}
d\bigl(T(m),T(m')\bigr) &\le \\
d\bigl(T(n),T(m)\bigr) + d\bigl(T(n),T(m')\bigr)
&< \epsilon.
\end{align*}\]
*** existence, uniqueness, and properties of a fixed point
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
({{c3::<<<Contraction mapping theorem>>>}}.)
If $(X,d)$ is a {{c1::nonempty}} and {{c1::complete}} metric space
and $T$ is {{c1::a contraction mapping on $X$}}, then
{{c2::\[\exists ! z \in X : T(z) = z,\]}}
i.e. $z$ is {{c2::the unique fixed point}},
and
{{c2::\[\forall x \in X : \lim_{n \rightarrow \infty} T^n(x) = z,\]}}
where {{c2::$\forall n \in \mathbb{N}$ : $T^n(x)$ :=
$\underset{n \text{ times} }{T(T(\cdots T}(x)))$}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
(Contraction mapping theorem.)
If $(X,d)$ is a nonempty and complete metric space
and $T$ is a contraction mapping on $X$, prove that
\[\exists ! z \in X : T(z) = z\]
and
\[\forall x \in X : \lim_{n \rightarrow \infty} T^n(x) = z,\]
where $\forall n \in \mathbb{N}$ : $T^n(x)$ :=
$\underset{n \text{ times} }{T(T(\cdots T}(x)))$.
***** Back
For $x \in X$,
$T(x)$ is Cauchy by the orbit lemma,
and since $(X,d)$ is complete it converges to some point $z \in X$.
Then $z$ is a fixed point of $T$ because
\[\begin{align*}
T^n(x) \rightarrow z
&\implies T(T^n(x)) \rightarrow T(z) \\
&\implies T(T^n(x)) = T^{n+1}(x) \rightarrow z = T(z),
\end{align*}\]
and is its unique fixed point because
\[T(z) = z \land T(z') = z'
\implies d(z,z') \le c \cdot d(z,z') \iff d(z,z') = 0.\]
**** example
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
$x \mapsto \frac{x}{2}$ is a contraction mapping on $(\mathbb{R},|\cdot|)$
with fixed point $z$ = {{c1::$0$}}.
** iterated function systems and fixed point sets
$\mathcal{K}(X)$ henceforth denotes the set of compact subsets of a set $X$.
*** COMMENT from PS2
Define a metric space $(X,d_H)$
such that $X$ is the set of compact subsets of $\mathbb{R}$
and $d_H$ is the Hausdorff distance.
Problem (PS2): $F$ : $(X,d_H) \rightarrow (X,d_H)$
is a contracting map.
*** fixed point set of a union of contraction mapping images of compact sets
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $m \in \mathbb{Z}_+$,
$\left\{T_n : \mathbb{R}^d \rightarrow \mathbb{R}^d\right\}_{n \in [m]}$
are contraction mappings,
and
{{c1::\[F : \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr) \rightarrow \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr) : A \mapsto = \bigcup_{n \in [m]} T_n(A),\]}}
then
{{c3::\[\exists ! A \in \mathcal{K}(\mathbb{R}^d) : F(A) = A.\]}}
This set is the {{c3::<<<fixed point set>>>}} of $F$.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
For $m \in \mathbb{Z}_+$
and contraction mappings
$\left\{T_n : \mathbb{R}^d \rightarrow \mathbb{R}^d\right\}_{n \in [m]}$,
let
\[F : \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr) \rightarrow \bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr)\]
such that
$F(A)$ = $\bigcup_{n \in [m]} T_n(A)$.
Prove that
\[\exists ! A \in \mathcal{K}(X) : F(A) = A.\]
***** Back
$F$ is a contraction mapping (to be demonstrated in problem set 2),
and $\bigl(\mathcal{K}(X),d_H\bigr)$ is a complete metric space (???).
A unique fixed point set thus exists by the contraction mapping theorem.
**** Cantor set
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
Let $T_0,T_1$ : $\mathbb{R} \rightarrow \mathbb{R}$ such that
$T_0(x)$ := {{c1::$\frac{x}{3}$}} and
$T_1(x)$ := {{c1::$\frac{x+2}{3}$}} and
$F(A)$ : $\mathcal{K}(\mathbb{R}) \rightarrow \mathcal{K}(\mathbb{R})$ such that
$F(A)$ := $T_0(A) \cup T_1(A)$.
Then

$F\bigl([0,1]\bigr)$ =
{{c3::$T_0\bigl([0,1]\bigr) \cup T_1\bigl([0,1]\bigr)$ = $\left[0,\frac{1}{3}\right] \cup \left[\frac{2}{3},1\right]$}},

and the {{c2::fixed point set}} of $F$ is {{c4::the middle-thirds Cantor set}}.
**** iterated function systems
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
If $T_0, T_1$ : $\mathbb{R}^d \rightarrow \mathbb{R}^d$
are {{c2::contraction mappings}} and
$F$ : $\bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr)$
$\rightarrow$
$\bigl(\mathcal{K}(\mathbb{R}^d),d_H\bigr)$
such that
$F(A)$ = $T_0(A) \cup T_1(A)$,
then the composition of $F$ with itself is

{{c1::\[F^2(A) = T_0\bigl(T_0(A)\bigr) \cup T_0\bigl(T_1(A)\bigr) \cup T_1\bigl(T_0(A)\bigr) \cup T_1\bigl(T_1(A)\bigr).\]}}
** basis for a topology
*** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
A {{c1::basis}} $\mathcal{B}$ for a topology $\mathcal{T}$
is {{c2::a collection of open sets such that $\forall A \in \mathcal{T}$ : $\exists \{A_\alpha\}_{\alpha \in I} \subseteq \mathcal{B}$ : $A = \bigcup_{\alpha \in I} A_\alpha$}}.
*** open intervals in R
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
{{c1::The open intervals}} form a basis for {{c2::the standard topology on $\mathbb{R}$}}.
*** open balls in a metric space
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For a metric space $(X,d)$,
{{c1::$\bigl\{B(x,\epsilon) \bigm| x \in X, \epsilon > 0\bigr\}$}}
forms a basis for {{c2::the open sets in $X$}}.
*** basis is an open cover
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $\mathcal{B}$ is a basis for the topology in $X$, then
$\forall x \in X$ :
{{c1::$\exists U \in \mathcal{B}$ : $x \in U$}}.
*** intersection of sets in a basis
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $\mathcal{B}$ is a basis for the topology $\mathcal{T}$ in $X$, then
{{c1::$\bigl[U,U' \in \mathcal{B} \land x \in U \cap U'\bigr]$}}
$\implies$
{{c2::$\exists U'' \in \mathcal{T}$ : $x \in U'' \subseteq U \cap U'$}}.
*** basis defines continuity of a function
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
If $f$ : $X \rightarrow Y$ for {{c3::topological spaces}} $X$ and $Y$
and $\mathcal{B}$ is a basis for the topology in $Y$,
then {{c1::$f$ is continuous}} iff {{c2::$\forall U \in \mathcal{B}$ : $f^{-1}(U)$ is open in $X$}}.
** product topologies
*** cylinder sets
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** Cloze
For {{c3::topological spaces}}
$\bigl\{X_\alpha\bigr\}_{\alpha \in I}$,
{{c1::$\prod_{\alpha \in I} A_\alpha$}}
is {{c4::a cylinder set}} in
$X$ :=
{{c2::$\prod_{\alpha \in I} X_\alpha$}}
iff
{{c1::$\forall \alpha \in I$ : $A_\alpha$ is open in $X_\alpha$}}.
**** open rectangles are cylinder sets in R^2
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
If $X$ := $\mathbb{R}^2$ = $\mathbb{R} \times \mathbb{R}$,
then $\forall$ {{c3::open intervals $(a,b), (a',b') \subseteq \mathbb{R}$}} :
{{c1::$(a,b) \times (a',b')$}}
is {{c2::a cylinder set}} in $X$.
**** basis for a product topology
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For {{c3::topological spaces}}
$\bigl\{X_\alpha\bigr\}_{\alpha \in I}$,
consider a {{c1::cylinder set $\prod_{\alpha \in I} A_\alpha$}} in
$X$ := {{c2::$\prod_{\alpha \in I} X_\alpha$}} such that
{{c1::$\exists I' \subseteq I$ : $\bigl[|I'| \in \mathbb{N} \land \forall \alpha \in I \setminus |I'|$ : $A_\alpha = X_\alpha\bigr]$}}.
These base cylinder sets form a basis for {{c4::the product topology on $X$}}.
*** projection maps
**** definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
***** Cloze
For a (possibly uncountable) sequence
$x$ := $(x_\alpha)_{\alpha \in I}$, the function

{{c3::$\pi_\alpha(x)$}} := {{c1::$x_\alpha$}}

is {{c2::a <<<projection map>>>}}.
*** continuity of functions with a product space codomain
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
**** COMMENT wtf
For topological spaces
$\{X_\alpha\}_{\alpha \in I}$, let
{{c1::\[f : Y \rightarrow \prod_{\alpha \in I} X_\alpha.\]}}
For $\alpha \in I$, let
{{c1::\[f_\alpha : Y \rightarrow X_\alpha : y \mapsto \pi_\alpha\bigl(f(y)\bigr).\]}}
Then
{{c2::\[F : Y \rightarrow \prod_{\alpha \in I} X_\alpha : y \mapsto \bigl(f_\alpha(y)\bigr)_{\alpha \in I}.\]}}
is {{c2::continuous}}
iff {{c3::$\forall \alpha \in I$ : $f_\alpha$ is continuous}}.
**** Cloze
For topological spaces
$\{X_\alpha\}_{\alpha \in I}$ let
{{c1::\[f : Y \rightarrow \prod_{\alpha \in I} X_\alpha,\]}}
and for $\alpha \in I$ let
{{c1::\[f_\alpha : Y \rightarrow X_\alpha : y \mapsto \pi_\alpha\bigl(f(y)\bigr).\]}}
Then {{c2::$f$ is continuous}}
iff {{c3::$\forall \alpha \in I$ : $f_\alpha$ is continuous}}.
**** proof
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:END:
***** Front
For topological spaces
$\{X_\alpha\}_{\alpha \in I}$, let
\[f : Y \rightarrow \prod_{\alpha \in I} X_\alpha,\]
and for $\alpha \in I$ let
\[f_\alpha : Y \rightarrow X_\alpha : y \mapsto \pi_\alpha\bigl(f(y)\bigr).\]
Then $f$ is continuous
iff $\forall \alpha \in I$ : $f_\alpha$ is continuous.
***** Back
Suppose $f$ is continuous.
Then, for $\alpha' \in I$ and an open set $U \subseteq X_{\alpha'}$,
\[f_{\alpha'}^{-1}(U) = f^{-1}\left(U \times \prod_{\alpha \in I \setminus \{\alpha'\}} X_\alpha\right)\]
is open as the preimage of a base cylinder set
in $\prod_{\alpha \in I} X_\alpha$.

Suppose $\forall \alpha \in I$ : $f_\alpha$ is continuous.
It suffices to verify that the preimage of $f$
for base a cylinder set $U$
is open.
Let $I' \subseteq I$ be a finite index subset for which
\[U = \prod_{\alpha \in I'} A_\alpha \times \prod_{\alpha \in I \setminus I'} X_\alpha.\]
Then
\[\begin{align*}
f^{-1}(U)
&= \left(\bigcap_{\alpha \in I'} f_{\alpha}^{-1}(A_\alpha)\right) \cap \left(\bigcap_{\alpha \in I \setminus I'} f_{\alpha}^{-1}(X_\alpha)\right) \\
&= \bigcap_{\alpha \in I'} f_{\alpha}^{-1}(A_\alpha)
\end{align*}\]
is open in $Y$
as the finite intersection of open sets in $Y$.
